services:
  - postgresql
before_script:
  - psql -c 'create database coherence_test;' -U postgres
language: elixir
elixir:
  - 1.4
  - 1.3
otp_release:
  - 20.0
  - 19.3
  - 18.3
sudo: false
notification:
  recipients:
    - smpallen99@yahoo.com
