services:
  - postgresql
before_script:
  - psql -c 'create database coherence_test;' -U postgres
language: elixir
elixir:
  - 1.3.0
otp_release:
  - 18.2.1
sudo: false
notification:
  recipients:
    - smpallen99@yahoo.com

